{% set name = "flac" %}
{% set version = "1.3.1" %}
{% set sha256 = "e0c23c92af0aac830683a6ab6784dd0c11aaf04249709b9d600675b3b2441c3e" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xiph/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002

requirements:
  build:
    - cmake  # [win]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gettext  # [unix]
    - libogg 1.3.*
  run:
    - libogg 1.3.*

test:
  commands:
    - test -f $PREFIX/bin/flac  # [unix]
    - test -f $PREFIX/bin/metaflac  # [unix]
    - test -f $PREFIX/lib/libFLAC.dylib  # [osx]
    - test -f $PREFIX/lib/libFLAC++.dylib  # [osx]
    - test -f $PREFIX/lib/libFLAC.so  # [linux]
    - test -f $PREFIX/lib/libFLAC++.so  # [linux]
    - if not exist %LIBRARY_LIB%\\libflac.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libflac.dll exit 1  # [win]

about:
  home: https://www.xiph.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.Xiph
  summary: "Flac audio format"
  description: Free Lossless Audio Codec.
  doc_url: https://wiki.xiph.org/

extra:
  recipe-maintainers:
    - dschreij
