{% set name = "flac" %}
{% set version = "1.5.0" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xiph/{{ name }}/archive/{{ version }}.tar.gz
  sha256: aea54ed186ad07a34750399cb27fc216a2b62d0ffcd6dc2e3064a3518c3146f8

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('libflac', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - cmake
    - pandoc
  host:
    - libogg {{ libogg }}
    # libiconv is included in libc for Linux and not used on Windows.
    - libiconv {{ libiconv }}  # [osx]
    - gettext {{ gettext }}    # [unix]
  run:
    - libogg
    - libiconv  # [osx]

test:
  commands:
    - test -f $PREFIX/bin/flac                        # [unix]
    - test -f $PREFIX/bin/metaflac                    # [unix]
    - test -f $PREFIX/lib/libFLAC${SHLIB_EXT}         # [unix]
    - test -f $PREFIX/lib/libFLAC++${SHLIB_EXT}       # [unix]
    - if not exist %LIBRARY_LIB%\\FLAC++.lib exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\FLAC++.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\FLAC.lib exit 1     # [win]
    - if not exist %LIBRARY_BIN%\\FLAC.dll exit 1     # [win]
    - flac --version

about:
  home: https://www.xiph.org
  license: BSD-3-Clause AND GPL-2.0-or-later AND GFDL-1.1-or-later AND LGPL-2.1-or-later
  license_family: OTHER
  license_file: 
    - COPYING.Xiph
    - COPYING.FDL
    - COPYING.GPL
    - COPYING.LGPL
  summary: Flac audio format
  description: Free Lossless Audio Codec.
  doc_url: https://wiki.xiph.org
  dev_url: https://github.com/xiph/flac

extra:
  recipe-maintainers:
    - dschreij
    - martinRenou
    - matthiasdiener
