{% set name = "flac" %}
{% set version = "1.4.3" %}
{% set sha256 = "0a4bb82a30609b606650d538a804a7b40205366ce8fc98871b0ecf3fbb0611ee" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xiph/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libflac', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pandoc
  host:
    - gettext 0.21.0 # [unix]
    - libogg 1.3.5
    # libiconv is included in libc for Linux and not used on Windows.
    - libiconv 1.16  # [osx]
  run:
    - libogg 1.3.*
    - libiconv  # [osx]

test:
  commands:
    - test -f $PREFIX/bin/flac                        # [unix]
    - test -f $PREFIX/bin/metaflac                    # [unix]
    - test -f $PREFIX/lib/libFLAC${SHLIB_EXT}         # [unix]
    - test -f $PREFIX/lib/libFLAC++${SHLIB_EXT}       # [unix]
    - if not exist %LIBRARY_LIB%\\FLAC++.lib exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\FLAC++.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\FLAC.lib exit 1     # [win]
    - if not exist %LIBRARY_BIN%\\FLAC.dll exit 1     # [win]
    - flac --version

about:
  home: https://www.xiph.org/
  license: BSD-3-Clause AND GFDL-1.2-only AND GPL-2.0-only
  license_family: OTHER
  license_file: 
    - COPYING.Xiph
    - COPYING.FDL
    - COPYING.GPL
  summary: Flac audio format
  description: Free Lossless Audio Codec.
  doc_url: https://wiki.xiph.org/
  dev_url: https://github.com/xiph/flac

extra:
  recipe-maintainers:
    - dschreij
    - martinRenou
    - matthiasdiener
