{% set name = "flac" %}
{% set version = "1.3.3" %}
{% set sha256 = "668cdeab898a7dd43cf84739f7e1f3ed6b35ece2ef9968a5c7079fe9adfe1689" %}

package:
  name: lib{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xiph/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - add_libm_to_flac.patch          # [linux]
    - add_libm_to_metaflac.patch      # [linux]
    - add_libm_to_test_streams.patch  # [linux]
    - fix_pkgconfig.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('libflac', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - gettext  # [unix]
    - libogg 1.3.*
  run:
    - libogg 1.3.*

test:
  commands:
    - test -f $PREFIX/bin/flac                        # [unix]
    - test -f $PREFIX/bin/metaflac                    # [unix]
    - test -f $PREFIX/lib/libFLAC${SHLIB_EXT}         # [unix]
    - test -f $PREFIX/lib/libFLAC++${SHLIB_EXT}       # [unix]
    - if not exist %LIBRARY_LIB%\\FLAC++.lib exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\FLAC++.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\FLAC.lib exit 1     # [win]
    - if not exist %LIBRARY_BIN%\\FLAC.dll exit 1     # [win]

about:
  home: https://www.xiph.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.Xiph
  summary: "Flac audio format"
  description: Free Lossless Audio Codec.
  doc_url: https://wiki.xiph.org/

extra:
  recipe-maintainers:
    - dschreij
    - martinRenou
