travis:
  secure:
    BINSTAR_TOKEN: SV+RATIBLOC79OrenQIo9EIHqmUJdzJYZBEJDpnbbwVMEGHfc0ToIyHZXajhc2ANVFlEBh6TxJoeRXFOPkaofVJ60D2J/NMPFfa4BDIgb1pO56H92NLMHVpV96waUpwstpyVeEPdxrzh/sM1n/xT1ODqFO9qJ9jBjfZLVjDEhxgsJu4y90pZz+x0gNyXG75zlDi6IJb6ueqr1T6JfiOjLObDxHk+x5uxButAxfSKDgYQdLwOWbC6VljxRTB8koXUwC6Tk8RWcMULHq3GCeAA4V2mR6nWxeEIIZLv3J3MIZGAdScxnkCrvHcUZoZdLM/6B3XKhuSmYGerJrIQS6Zc8IB0zIQPLDIsQ8fAC9OyEX/oGaHEBmBai1wlYJz+XEUzAYKGTvMHbcvBIVdMdCcX2PnkY6xJbct6ZMCGOv5A302y7gd450VVhgbwmkiopyyJciYHSy4bP20cIN3dINSbpNr1LG+FOm0lCQCMv8E6g0V7S7X27iZirr/y3XWDNkGubmD1Qi6bsngghH4fq5DoiHEJMYwnvVO34gK1+no6qbdE8LMZaf1NLr6HMXbJ0eMfg6uhddSQNTcP+9LsB60CjNN0UATR1D7kc75CU+U4vY++mqa3oyLcKdWtvvWeI0EkNxp9kGBvLp+IM5OaFL2v48ArI1yBL7ndVP0hd1S+QEU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
