travis:
  secure:
    BINSTAR_TOKEN: OcibFvGjGBjLRNi9MP5KOSen6ADRPoOhoWjP7Du62FGsWpChrsbwbKWl7V+Xvvja83eVP5/zyu//8fgCqvFqxU0lZsIwZILaBFal4JipNsrVepQWxKJrMo3HLGiea3sjDil8VTSe1vxyAoSVb0KqihkOq1e1j3t30Di/YAHqt9aUTbrWmTBzIMRGq6ILw1VJdKEcNHAK5KCysppMu4VAIF1uF174hZf8LsTUn9A5FyA+hYS/nzTNTZf0uaw03DbpnnUHuBroHRo/32X6aXrklk606QwwbYAwimWY9hx+B+ObkjouM6gIhipQ/8L98lR/0v5awf0RlbvLdJHooskdAYwdM0lOowwYIHsQV0TEeBjwNb9TW89BsadF/9/8avkEs5Hrb8pKhJQrTKUjLxMr4CEiERRBQlHOKPIf+HILcsypHpxdXmbZSWOfis4q9nr+mMYOihWhMX8oWIYEGS/ZRylYyvVIdmI7fHveniSU5XUllVN1j8qXmp9bH5SXgNvUQGy402u8cx/pGEgYOcXnsdI3c2AZYvHHyE+4BsAJZeIogx+kA7ruVf7j1yjBSSLi7p8a2NHfnL72K0eabFdRMJjC9R2R+cvJ++68W2N6knSUCyBExs6EFH3SfU3f6YoU20X3/ijFBo6eIr/KRSWKR7631JAJaf6KZb1jZVX14uI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
